---
kind: pipeline
type: kubernetes
name: default

clone:
  disable: true

steps:
  - name: update_cd
    image: docker:git
    environment:
      POMPA_CD_DEPLOY_KEY:
        from_secret: pompa_cd_deploy_key
    commands:
      - mkdir -p ~/.ssh
      - echo -ne "$POMPA_CD_DEPLOY_KEY" > ~/.ssh/id_rsa
      - ssh-keyscan -H github.com > ~/.ssh/known_hosts
      - chmod 600 ~/.ssh/id_rsa ~/.ssh/known_hosts
      - mkdir pompa-cd
      - cd pompa-cd
      - git init
      - git config user.email "drone@nalewajski.pl"
      - git config user.name "Drone CI"
      - git remote add origin git@github.com:m1nl/pompa-cd.git
      - git remote add upstream https://github.com/m1nl/pompa-docker.git
      - git fetch origin master
      - git fetch upstream master
      - git checkout -b master --track origin/master
      - git pull upstream master --rebase
      - git push origin master --force
