version: "3.3"
services:
  app:
    build: "./app"
    depends_on:
      - redis
      - db
    volumes:
      - "pompa_storage:/app/storage"
      - "pompa_shared_tmp:/app/tmp/shared"
    environment: &environment
      - POMPA_DB=pompa
      - POMPA_DB_USERNAME=pompa
      - POMPA_DB_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_db_password
    secrets:
      - pompa_db_password
      - secret_key_base
      - active_record_primary_key
      - active_record_deterministic_key
      - active_record_key_derivation_salt
  facade:
    build: "./facade"
    volumes:
      - "pompa_shared_tmp:/var/www/pompa-tmp"
    environment: *environment
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - app
  redis:
    build: "./redis"
    sysctls:
      net.core.somaxconn: "511"
    volumes:
      - "redis_data:/data"
  db:
    build: "./db"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment: *environment
    secrets:
      - pompa_db_password
      - postgres_db_password
volumes:
  pompa_storage:
  pompa_shared_tmp:
  redis_data:
  postgres_data:
secrets:
  pompa_db_password:
    file: ./.secrets/pompa_db_password
  postgres_db_password:
    file: ./.secrets/postgres_db_password
  secret_key_base:
    file: ./.secrets/secret_key_base
  active_record_primary_key:
    file: ./.secrets/active_record_primary_key
  active_record_deterministic_key:
    file: ./.secrets/active_record_deterministic_key
  active_record_key_derivation_salt:
    file: ./.secrets/active_record_key_derivation_salt
