active_record_encryption:
  primary_key: <%= File.read('/run/secrets/active_record_primary_key') %>
  deterministic_key: <%= File.read('/run/secrets/active_record_deterministic_key') %>
  key_derivation_salt: <%= File.read('/run/secrets/active_record_key_derivation_salt') %>
