redis_default: &redis_default
  driver: hiredis
  url: "redis://redis"

default: &default
  trusted_proxies:
    - "web"
  endpoints:
    admin: true
    public: true
    sidekiq_console: true
  template:
    base_url: "<%= ENV.fetch('POMPA_BASE_URL') { 'http://localhost:8082/' } %>"
  redis:
    <<: *redis_default

production:
  <<: *default
  redis:
    <<: *redis_default

development:
  <<: *default
  log_level: "debug"

test:
  <<: *default
